# Generated by Django 5.2.17 on 2026-10-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
