# Generated by Django 5.2.17 on 2026-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(unique=True)),
                ('ville_dep', models.CharField()),
                ('ville_arr', models.CharField()),
                ('poid', models.FloatField()),
                ('date_souhaitte', models.DateField(auto_now_add=True)),
                ('descreption', models.TextField()),
                ('status', models.CharField(choices=[('publiee', 'publiee'), ('attribuee', 'attribuee'), ('en cour', 'en cour'), ('livre', 'livre'), ('annulee', 'annulee')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
