# Generated by Django 5.2.17 on 2026-09-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExpertionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai', models.IntegerField()),
                ('status', models.CharField(choices=[])),
                ('date_proposition', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('expertion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertions', to='ExpertionApp.expertion')),
            ],
        ),
    ]
