# Generated by Django 5.2.17 on 2026-10-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
        ('ExpeditionsApp', '0001_initial'),
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('proposee', 'proposee'), ('acceptee', 'acceptee'), ('refusee', 'refusee'), ('retiree', 'retiree')], default='proposee')),
                ('date_proposition', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='EntrepriseApp.entreprise')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition', to='ExpeditionsApp.expedition')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='VehiculeApp.vehicule')),
            ],
        ),
    ]
