# Generated by Django 5.2.17 on 2026-09-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OffeApp', '0001_initial'),
        ('vehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreapp',
            name='vehicule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='vehiculeApp.vehicule'),
        ),
    ]
