# Generated by Django 5.2.17 on 2026-09-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_utilisateur_entreprise_gerant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=100, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camionnette', 'amionnette'), ('fourgon', 'fourgon'), ('ca_pot', 'camion porteur'), ('sem_remr', 'semi-remorque')], max_length=20)),
                ('capacite_kg', models.IntegerField()),
                ('dsiponible', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('entreprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
