# Generated by Django 5.2.17 on 2026-10-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=11, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camionnette', 'camionnette'), ('fourgon', 'fourgon'), (' camion porteur', ' camion porteur'), (' semi-remorque', ' semi-remorque')])),
                ('capacite_kg', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
