# Generated by Django 5.2.17 on 2026-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('matricule_fiscale', models.CharField(max_length=17, unique=True)),
                ('type_entrprise', models.CharField(choices=[('Trans', 'transpoteur'), ('Char', 'chargeur')], default='chargeur', max_length=100)),
                ('addresse', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
